name: Run Daily Forecasting Pipeline

on:
  workflow_dispatch: # يسمح بالتشغيل اليدوي من تبويب Actions في GitHub
  schedule:
    # يشغل في الساعة 01:00 بالتوقيت العالمي الموحد (UTC) كل يوم (الساعة 4:00 فجراً بتوقيت السعودية)
    # يمكنك تعديل التوقيت: مثلاً '0 3 * * *' لتشغيله الساعة 3:00 صباحاً بتوقيت UTC (الساعة 6:00 صباحاً بتوقيت السعودية)
    - cron: '0 1 * * *'

jobs:
  forecast:
    runs-on: ubuntu-latest # تشغيل على أحدث نسخة من نظام تشغيل أوبونتو (Linux)
    permissions:
      contents: write # إضافة هذه الأسطر الجديدة لتصحيح مشكلة الصلاحيات

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # يسحب الكود من مستودع GitHub

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # استخدم نفس إصدار بايثون الذي تستخدمه لمشروعك (مثلاً 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # تثبيت المكتبات من requirements.txt

    # --- تشغيل موديل الطقس ---
    - name: Run Weather Model (daily_forecast_pipeline.py)
      run: python daily_forecast_pipeline.py

    # --- تشغيل موديل تعليقات العملاء ---
    - name: Run Customer Comments Model (nlp_reviews_pipeline.py)
      run: python nlp_reviews_pipeline.py

    # --- تشغيل موديل خروج العملاء ---
    - name: Run Customer Churn Model (churn_model_pipeline.py)
      run: python churn_model_pipeline.py

    # --- تشغيل موديل السعر ---
    - name: Run Price Model (price_model_pipeline.py)
      run: python price_model_pipeline.py

    - name: Commit and Push new data (Automated)
      # هذه الخطوة تقوم بحفظ ودفع مخرجات الموديلز إلى GitHub
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data/forecast_results/weather_forecast.csv # إضافة ملف الطقس
        git add data/predictions/churn_predictions.csv # إضافة ملف تنبؤات الخروج
        git add data/sentiment_results/sentiment_analysis_results.csv # **هذا هو السطر الذي ينقصه الكود الذي أرسلته لي!**
        git commit -m "Automated: Update data from weather, churn, and sentiment models" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}