- name: Commit and Push new data (Automated)
  # هذه الخطوة تقوم بحفظ ودفع مخرجات الموديلز إلى GitHub
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"
    git add data/forecast_results/weather_forecast.csv # إضافة ملف الطقس
    git add data/predictions/churn_predictions.csv # إضافة ملف تنبؤات الخروج
    git add data/sentiment_results/sentiment_analysis_results.csv # إضافة ملف تحليل المشاعر
    git add data/pricing_results/optimal_prices.csv # **أضف هذا السطر الجديد!**
    git commit -m "Automated: Update data from all four models (weather, churn, sentiment, price)" || echo "No changes to commit"
    git push origin main
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}